### ISSUE TITLE
The ability to build for Windows using MXE

### ISSUE THREAD

**Issue by rawr51919** [MCPI-Revival/Ninecraft#22]
MXE is a cross-compiler toolchain that has sufficient equivalents of all the libraries needed to make this particular launcher buildable for Windows. Is that a planned feature?

The main website for it is https://mxe.cc

Sent to upstream via https://gitea.thebrokenrail.com/minecraft-pi-reborn/minecraft-pi-reborn/issues/92

**Comment by TheBrokenRail** [comment]
Cross-compiling is not and has never been the barrier to running Ninecraft on Windows.

I could use MinGW to compile Ninecraft itself for Windows. The issue is that it would be completely useless. This is because `libminecraftpe.so` itself is closed-source. It is an Android ARM32/x86 binary and always will be. I cannot change that without a full-blown de-compilation project like [ReMinecraftPE](https://github.com/ReMinecraftPE/mcpe). And that is way harder than it sounds.

To run Ninecraft on Windows, you would need to be able to run Linux binaries on Windows. And to do that, you would need to re-implement the Linux ABI on top of Windows. And that already exists, it's called WSL.
